# conflicts _redirects?;

# [[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200               # 200 = rewrite ( /=/  no URL change), 301= /=/something
#  force = true


# [[redirects]]
#  from = "/api/*"
#  to = "/.netlify/functions/api/:splat"
#  status = 200


# Move api/ into netlify/functions OR;
[build]
  command = "npm run build"  # or your build command (e.g., `webpack`)
  publish = "public"         # Webpack's output folder
  functions = "api"
# functions = "netlify/functions"          # Only if `api/` contains serverless functions;


[[headers]]
    for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "no-referrer"
	    cache-control = '''
	    max-age=0,
	    no-cache,
	    no-store,
	    must-revalidate'''

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# netlify/functions/api/hello.js becomes /.netlify/functions/api/hello.;
# You can redirect URLs to /.netlify/functions/api...:;