# conflicts _redirects?;

# [[redirects]]
#  from = "/api/*"
#  to = "/.netlify/functions/api/:splat"
#  status = 200              # 200 = rewrite (no URL change), 301= some url change
#  force = true


# Move api/ into netlify/functions OR;
[build]
  command = "npm run build"  # or your build command (e.g., `webpack`)
  publish = "public"         # Webpack's output folder
  functions = "public/api"   # "netlify/functions" # if `api/` serverless;


[[headers]]
    for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "no-referrer"
	    cache-control = '''
	    max-age=0,
	    no-cache,
	    no-store,
	    must-revalidate'''


# https://elegant-bubblegum-a62895.netlify.app/.netlify/functions/Login 
# You can redirect URLs to /.netlify/functions/...:;  actually without /api/
